title:            aslam | blog
description:      personal scrapbook of aslam abbas
url:              aslamabbas.github.io
signoff:          aslamabbas
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Email
    url:          mailto:aslam.abbas@outlook.com
    external:     true
  - name:         GitHub
    url:          http://github.com/aslamabbas
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
