title:            aslam | blog
description:      personal scrapbook of aslam
url:              aslamabbas.com
signoff:          aslamabbas

links:
  - name:         all-posts
    url:          /
  - name:         about
    url:          /about
  - name:         wishlist
    url:          http://www.amazon.in/gp/registry/wishlist/2N47HBSEOQ0G4/ref=topnav_lists_2
    external:     true
 
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
