title:            aslam | blog
description:      personal scrapbook of aslam abbas
url:              aslamabbas.github.io
signoff:          aslamabbas

links:
  - name:         Home
    url:          /
  - name:         About
    url:          /about
  - name:         Email
    url:          mailto:aslam.abbas@outlook.com
    external:     true
  - name:         GitHub
    url:          http://github.com/aslamabbas
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
